### ISSUE TITLE
Run a python script in lock screen

### ISSUE THREAD

**Issue by santoshmn26** [saksham-jain/Lock-Unlock-Laptop-PC-Screen-Using-Face-Recognition#1]
Hi I am working on a similar application, 
How do you keep the python script running in the lock screen

**Comment by saksham-jain** [comment]
Python script wont run on windows lock screen. You will have to turn off windows lock and use the python script.

**Comment by santoshmn26** [comment]
Thank you for your quick response, you mean disable windows lock?
Can you please explain?
